# Generated by Django 2.0.2 on 2018-03-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_frans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('topic', models.ManyToManyField(to='rest_api_frans.Topic')),
            ],
        ),
    ]
